# Generated by Django 5.2.10 on 2026-03-03 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='daily_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mission',
            unique_together={('title', 'skill')},
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['skill', 'level'], name='core_missio_skill_3332fd_idx'),
        ),
        migrations.AddField(
            model_name='dailymission',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mission'),
        ),
        migrations.AddField(
            model_name='dailymission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailymission',
            index=models.Index(fields=['user', 'date'], name='core_dailym_user_id_7c3abd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymission',
            unique_together={('user', 'date', 'mission')},
        ),
    ]
