# Generated by Django 5.2.10 on 2026-03-05 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailymission_attempt_daily_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mission'),
        ),
    ]
