# Generated by Django 5.2.10 on 2026-03-05 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attempt_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymission',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mission'),
        ),
    ]
