# Generated by Django 5.2.10 on 2026-03-05 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dailymission_mission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'mission', '-created_at'], name='core_attemp_user_id_f8a7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', '-created_at'], name='core_attemp_user_id_9a8cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'daily_date'], name='core_attemp_user_id_821232_idx'),
        ),
    ]
