# Generated by Django 5.2.10 on 2026-03-13 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userstreak'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='실전 모의고사', max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_min', models.PositiveIntegerField(default=40)),
                ('total_questions', models.PositiveIntegerField(default=40)),
                ('status', models.CharField(choices=[('in_progress', '진행중'), ('submitted', '제출완료'), ('expired', '시간종료')], default='in_progress', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSessionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.PositiveIntegerField()),
                ('user_answer_correct', models.BooleanField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.examsession')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mission')),
            ],
            options={
                'ordering': ['order_no'],
            },
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['user', '-started_at'], name='core_examse_user_id_d1e866_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['status'], name='core_examse_status_86672b_idx'),
        ),
        migrations.AddIndex(
            model_name='examsessionmission',
            index=models.Index(fields=['exam_session', 'order_no'], name='core_examse_exam_se_2e0914_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examsessionmission',
            unique_together={('exam_session', 'order_no')},
        ),
    ]
