# Generated by Django 5.2.10 on 2026-03-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_examsession_examsessionmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='attempts_synced',
            field=models.BooleanField(default=False),
        ),
    ]
