# Generated by Django 5.2.10 on 2026-03-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_useraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='answer_input_type',
            field=models.CharField(choices=[('none', '입력 없음'), ('text', '텍스트'), ('number', '숫자')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='mission',
            name='correct_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mission',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mission',
            name='question_type',
            field=models.CharField(choices=[('manual', '수동 확인형'), ('short_answer', '단답 입력형'), ('value_answer', '값 입력형')], default='manual', max_length=20),
        ),
    ]
