# Generated by Django 5.2.10 on 2026-03-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mission_answer_input_type_mission_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='submitted_answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
