# Generated by Django 5.2.10 on 2026-03-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_attempt_submitted_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='answer_input_type',
            field=models.CharField(choices=[('none', '입력 없음'), ('text', '텍스트'), ('number', '숫자'), ('date', '날짜')], default='none', max_length=20),
        ),
    ]
