# Generated by Django 5.2.10 on 2026-04-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_mission_answer_input_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='answer_schema',
            field=models.TextField(blank=True, default=''),
        ),
    ]
