# Generated by Django 5.2.10 on 2026-04-01 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_mission_answer_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('input_type', models.CharField(blank=True, default='', max_length=20)),
                ('submitted_answer', models.TextField(blank=True, default='')),
                ('correct_answer', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.attempt')),
            ],
            options={
                'indexes': [models.Index(fields=['attempt', 'is_correct'], name='core_attemp_attempt_1a9c48_idx'), models.Index(fields=['label', 'is_correct'], name='core_attemp_label_a5f075_idx')],
            },
        ),
    ]
