# Generated by Django 5.2.10 on 2026-04-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_attemptitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mission',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
