# Generated by Django 5.2.10 on 2026-04-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_mission_unique_together_mission_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='external_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
