# Generated by Django 5.2.10 on 2026-04-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_mission_external_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttemptItem',
        ),
    ]
