# Generated by Django 5.2.10 on 2026-04-23 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_attemptitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('skill_group', models.CharField(blank=True, default='', max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('set_type', models.CharField(choices=[('training', '훈련 세트'), ('review', '복습 세트'), ('exam_like', '실전형 세트')], default='training', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['skill_group', 'level'], name='core_proble_skill_g_9a1497_idx'), models.Index(fields=['set_type', 'is_active'], name='core_proble_set_typ_e5bd6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProblemSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('core', '핵심'), ('review', '복습'), ('challenge', '도전')], default='core', max_length=30)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problem_set_items', to='core.mission')),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.problemset')),
            ],
            options={
                'ordering': ['order_no'],
                'indexes': [models.Index(fields=['problem_set', 'order_no'], name='core_proble_problem_adfbd6_idx'), models.Index(fields=['mission'], name='core_proble_mission_03c9d5_idx')],
                'unique_together': {('problem_set', 'order_no')},
            },
        ),
    ]
