# Generated by Django 5.2.10 on 2026-04-23 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_problemset_problemsetitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSetSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', '진행중'), ('completed', '완료')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.problemset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemSetSessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.PositiveIntegerField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mission')),
                ('problem_set_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.problemsetsession')),
            ],
            options={
                'ordering': ['order_no'],
            },
        ),
        migrations.AddIndex(
            model_name='problemsetsession',
            index=models.Index(fields=['user', '-started_at'], name='core_proble_user_id_50b622_idx'),
        ),
        migrations.AddIndex(
            model_name='problemsetsession',
            index=models.Index(fields=['problem_set', '-started_at'], name='core_proble_problem_c0ec7f_idx'),
        ),
        migrations.AddIndex(
            model_name='problemsetsession',
            index=models.Index(fields=['status'], name='core_proble_status_3d911d_idx'),
        ),
        migrations.AddIndex(
            model_name='problemsetsessionitem',
            index=models.Index(fields=['problem_set_session', 'order_no'], name='core_proble_problem_65d97a_idx'),
        ),
        migrations.AddIndex(
            model_name='problemsetsessionitem',
            index=models.Index(fields=['mission'], name='core_proble_mission_2dd26a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='problemsetsessionitem',
            unique_together={('problem_set_session', 'order_no')},
        ),
    ]
