# Generated by Django 5.2.10 on 2026-04-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_problemsetsession_problemsetsessionitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='question_type',
            field=models.CharField(choices=[('manual', '수동 확인형'), ('short_answer', '단답 입력형'), ('value_answer', '값 입력형'), ('choice_one', '객관식 단일 선택형'), ('true_false', 'O/X 판단형'), ('error_detect', '오류 찾기형')], default='manual', max_length=20),
        ),
    ]
