# Generated by Django 5.2.10 on 2026-04-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_mission_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_quality_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mission',
            name='is_usable_for_set',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='quality_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
