# Generated by Django 5.2.10 on 2026-05-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_mission_is_quality_checked_mission_is_usable_for_set_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrongPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('skill', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['skill', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttemptWrongPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_patterns', to='core.attempt')),
                ('wrong_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.wrongpattern')),
            ],
            options={
                'unique_together': {('attempt', 'wrong_pattern')},
            },
        ),
    ]
