# Generated by Django 5.2.10 on 2026-05-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_wrongpattern_attemptwrongpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='wrong_pattern_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
