# Generated by Django 5.2.10 on 2026-05-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_mission_wrong_pattern_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='variation_group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
