# Generated by Django 6.0.6 on 2026-06-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_patterntrainingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='learning_type',
            field=models.CharField(choices=[('result', '결과 예측형'), ('feature', '기능 선택형'), ('error', '오류 진단형'), ('next_action', '다음 행동형'), ('procedure', '절차 순서형')], default='result', max_length=20),
        ),
    ]
