# Generated by Django 6.0.6 on 2026-06-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_mission_learning_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='quality_level',
            field=models.CharField(choices=[('basic', 'basic'), ('standard', 'standard'), ('practical', 'practical')], default='basic', max_length=20),
        ),
    ]
