# Generated by Django 6.0.6 on 2026-06-16 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_userevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=200)),
                ('inquiry_type', models.CharField(choices=[('premium', '프리미엄 신청'), ('bug', '오류 제보'), ('question', '일반 문의'), ('other', '기타 문의')], default='question', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', '새 문의'), ('in_progress', '처리 중'), ('done', '완료')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inquiry_type', 'status'], name='core_inquir_inquiry_863410_idx'), models.Index(fields=['-created_at'], name='core_inquir_created_f88d5c_idx')],
            },
        ),
    ]
