# Generated by Django 6.0.6 on 2026-06-18 19:56

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_SUBJECT = {
    "code": "comhwal2",
    "name": "컴활 2급",
    "description": "컴퓨터활용능력 2급 실기/필기 대비 학습",
}


def ensure_default_subject(apps, schema_editor):
    Subject = apps.get_model("core", "Subject")
    Mission = apps.get_model("core", "Mission")

    subject, _ = Subject.objects.get_or_create(
        code=DEFAULT_SUBJECT["code"],
        defaults={
            "name": DEFAULT_SUBJECT["name"],
            "description": DEFAULT_SUBJECT["description"],
            "is_active": True,
        },
    )
    Mission.objects.filter(subject__isnull=True).update(subject=subject)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='core.subject'),
        ),
        migrations.RunPython(ensure_default_subject, migrations.RunPython.noop),
    ]
