# Generated by Django 6.0.6 on 2026-06-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_subject_mission_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='chapter_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mission',
            name='chapter_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mission',
            name='course',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mission',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('하', '하'), ('중', '중'), ('상', '상')], default='', max_length=1),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['subject', 'course', 'chapter_code'], name='core_missio_subject_785681_idx'),
        ),
    ]
