# Generated by Django 6.0.6 on 2026-08-31 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_learning_configuration(apps, schema_editor):
    Subject = apps.get_model("core", "Subject")
    Mission = apps.get_model("core", "Mission")
    WrongPattern = apps.get_model("core", "WrongPattern")
    CertificationPolicy = apps.get_model("core", "CertificationPolicy")
    CertificationArea = apps.get_model("core", "CertificationArea")

    default_subject = Subject.objects.filter(code="comhwal2").first()
    if default_subject:
        WrongPattern.objects.filter(subject__isnull=True).update(subject=default_subject)

    logistics = Subject.objects.filter(code="logistics").first()
    if not logistics:
        return
    chapters = (
        Mission.objects.filter(subject=logistics)
        .exclude(chapter_code="")
        .values("chapter_code", "chapter_name", "course")
        .distinct()
    )
    for chapter in chapters:
        code = f"LOGISTICS_{chapter['chapter_code']}"
        WrongPattern.objects.update_or_create(
            subject=logistics, code=code,
            defaults={
                "name": f"{chapter['chapter_name']} 핵심 개념 혼동",
                "skill": chapter["chapter_code"],
                "description": f"{chapter['course']}의 반복 개념 오답",
                "minimum_evidence": 2,
            },
        )
        Mission.objects.filter(subject=logistics, chapter_code=chapter["chapter_code"]).update(
            wrong_pattern_code=code, variation_group=code
        )

    policy, _ = CertificationPolicy.objects.update_or_create(
        subject=logistics,
        defaults={
            "passing_score": 60, "minimum_area_score": 40,
            "exam_question_count": 200, "exam_duration_minutes": 200,
            "readiness_min_attempts": 50, "recent_attempt_window": 100,
            "required_mock_exam_count": 1,
            "source_note": "과목별 과락과 전체 평균을 함께 반영하는 물류관리사 준비도 정책",
        },
    )
    for order, (code, name, prefix) in enumerate([
        ("LM", "물류관리론", "LM"), ("TR", "화물운송론", "TR"),
        ("IL", "국제물류론", "IL"), ("WH", "보관하역론", "WH"),
        ("LW", "물류관련법규", "LW"),
    ], start=1):
        CertificationArea.objects.update_or_create(
            policy=policy, code=code,
            defaults={"name": name, "course": name, "chapter_prefix": prefix,
                      "weight": 20, "passing_floor": 40, "order": order},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_mission_learning_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(blank=True, default='', max_length=100)),
                ('chapter_prefix', models.CharField(blank=True, default='', max_length=20)),
                ('weight', models.PositiveSmallIntegerField(default=20)),
                ('passing_floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CertificationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_score', models.PositiveSmallIntegerField(default=60)),
                ('minimum_area_score', models.PositiveSmallIntegerField(default=40)),
                ('exam_question_count', models.PositiveIntegerField(default=0)),
                ('exam_duration_minutes', models.PositiveIntegerField(default=0)),
                ('readiness_min_attempts', models.PositiveIntegerField(default=30)),
                ('recent_attempt_window', models.PositiveIntegerField(default=100)),
                ('required_mock_exam_count', models.PositiveSmallIntegerField(default=1)),
                ('source_note', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('suspected', '의심'), ('active', '약점 확정'), ('training', '집중 훈련 중'), ('review_due', '재평가 대기'), ('mastered', '극복'), ('relapsed', '재발')], default='suspected', max_length=20)),
                ('severity', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('recent_failure_count', models.PositiveIntegerField(default=0)),
                ('consecutive_successes', models.PositiveIntegerField(default=0)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_detected_at', models.DateTimeField(auto_now=True)),
                ('last_trained_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='wrongpattern',
            name='minimum_evidence',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='wrongpattern',
            name='remediation_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wrongpattern',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_patterns', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='wrongpattern',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='wrongpattern',
            constraint=models.UniqueConstraint(fields=('subject', 'code'), name='unique_wrong_pattern_per_subject'),
        ),
        migrations.AddField(
            model_name='certificationpolicy',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification_policy', to='core.subject'),
        ),
        migrations.AddField(
            model_name='certificationarea',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.certificationpolicy'),
        ),
        migrations.AddField(
            model_name='userweakness',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_weaknesses', to='core.subject'),
        ),
        migrations.AddField(
            model_name='userweakness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userweakness',
            name='wrong_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_weaknesses', to='core.wrongpattern'),
        ),
        migrations.AddConstraint(
            model_name='certificationarea',
            constraint=models.UniqueConstraint(fields=('policy', 'code'), name='unique_certification_area'),
        ),
        migrations.AddIndex(
            model_name='userweakness',
            index=models.Index(fields=['user', 'subject', 'status'], name='core_userwe_user_id_b15168_idx'),
        ),
        migrations.AddIndex(
            model_name='userweakness',
            index=models.Index(fields=['user', 'next_review_at'], name='core_userwe_user_id_df14bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='userweakness',
            constraint=models.UniqueConstraint(fields=('user', 'subject', 'wrong_pattern'), name='unique_user_subject_weakness'),
        ),
        migrations.RunPython(seed_learning_configuration, migrations.RunPython.noop),
    ]
