# Generated by Django 6.0.6 on 2026-09-01 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_quick_wrong_reasons(apps, schema_editor):
    WrongReason = apps.get_model("core", "WrongReason")
    for name in ("개념을 몰랐음", "비슷한 선택지와 혼동", "문제를 잘못 읽음", "계산·적용 실수", "시간 부족으로 추측"):
        WrongReason.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_archive_stale_logistics_patterns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='confidence_level',
            field=models.CharField(blank=True, choices=[('guessed', '찍었어요'), ('unsure', '헷갈렸어요'), ('certain', '확실했어요')], default='', max_length=12),
        ),
        migrations.CreateModel(
            name='StudyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_exam_date', models.DateField(blank=True, null=True)),
                ('daily_minutes', models.PositiveSmallIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfusionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.TextField(blank=True, default='')),
                ('correct_answer', models.TextField(blank=True, default='')),
                ('times_seen', models.PositiveIntegerField(default=1)),
                ('mastered', models.BooleanField(default=False)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confusion_cards', to='core.mission')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confusion_cards', to='core.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confusion_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'subject', 'mastered', 'next_review_at'], name='core_confus_user_id_27a865_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'mission', 'selected_answer'), name='unique_user_confusion_choice')],
            },
        ),
        migrations.RunPython(seed_quick_wrong_reasons, migrations.RunPython.noop),
    ]
