# Generated by Django 6.0.8 on 2026-09-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_learning_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptunit',
            name='references',
            field=models.JSONField(blank=True, default=list, help_text='개념 검수 근거 URL 목록. 문제 원출처와 구분합니다.'),
        ),
        migrations.AddField(
            model_name='examsessionmission',
            name='draft_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='examsessionmission',
            name='draft_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsessionmission',
            name='submitted_answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
