# Generated by Django 6.0.8 on 2026-09-04 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_exam_reliability_and_review_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='mode_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='examsession',
            name='previous_sitting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_sitting', to='core.examsession'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('waiting', '시작 대기'), ('in_progress', '진행중'), ('submitted', '제출완료'), ('expired', '시간종료')], default='in_progress', max_length=20),
        ),
    ]
