# Generated by Django 6.0.8 on 2026-09-11 22:42

import hashlib
import json

from django.db import migrations, models


CHOICE_GRADING_TYPES = {"choice_one", "true_false", "error_detect"}


def fingerprint(payload):
    encoded = json.dumps(
        payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def content_payload(mission):
    return {
        "title": mission.title or "",
        "prompt": mission.prompt or "",
        "answer_schema": mission.answer_schema or "",
        "correct_answer": mission.correct_answer or "",
        "answer_key": mission.answer_key or "",
        "explanation": mission.explanation or "",
        "choice_explanations": mission.choice_explanations or {},
        "concept_summary": mission.concept_summary or "",
        "exam_tip": mission.exam_tip or "",
        "question_type": mission.question_type or "",
        "answer_input_type": mission.answer_input_type or "",
    }


def grading_payload(mission):
    payload = {
        "question_type": mission.question_type or "",
        "answer_input_type": mission.answer_input_type or "",
        "correct_answer": mission.correct_answer or "",
        "answer_key": mission.answer_key or "",
    }
    if mission.question_type not in CHOICE_GRADING_TYPES:
        payload["answer_schema"] = mission.answer_schema or ""
    return payload


def backfill_versions_and_snapshots(apps, schema_editor):
    Mission = apps.get_model("core", "Mission")
    Attempt = apps.get_model("core", "Attempt")

    mission_cache = {}
    mission_batch = []
    for mission in Mission.objects.all().iterator(chunk_size=500):
        mission.content_version = 1
        mission.content_fingerprint = fingerprint(content_payload(mission))
        mission.grading_fingerprint = fingerprint(grading_payload(mission))
        mission_cache[mission.pk] = mission
        mission_batch.append(mission)
    if mission_batch:
        Mission.objects.bulk_update(
            mission_batch,
            ["content_version", "content_fingerprint", "grading_fingerprint"],
            batch_size=500,
        )

    attempt_batch = []
    for attempt in Attempt.objects.all().iterator(chunk_size=500):
        mission = mission_cache[attempt.mission_id]
        attempt.mission_content_version = mission.content_version
        attempt.mission_content_fingerprint = mission.content_fingerprint
        attempt.mission_grading_fingerprint = mission.grading_fingerprint
        attempt.mission_snapshot = {
            "external_id": mission.external_id,
            "content_version": mission.content_version,
            "content_fingerprint": mission.content_fingerprint,
            "grading_fingerprint": mission.grading_fingerprint,
            **content_payload(mission),
        }
        attempt_batch.append(attempt)
    if attempt_batch:
        Attempt.objects.bulk_update(
            attempt_batch,
            [
                "mission_content_version",
                "mission_content_fingerprint",
                "mission_grading_fingerprint",
                "mission_snapshot",
            ],
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_examsession_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='grading_invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='grading_invalidation_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='attempt',
            name='grading_valid',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='mission_content_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='attempt',
            name='mission_content_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attempt',
            name='mission_grading_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='attempt',
            name='mission_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mission',
            name='content_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mission',
            name='content_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mission',
            name='grading_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.RunPython(backfill_versions_and_snapshots, migrations.RunPython.noop),
    ]
