"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlsplit

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-x^30!!jd+-6^v0kzk+wqogf&=d(#hk#xc5(=&4ul^mnkq&y#c0'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []

import os

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv


load_dotenv(BASE_DIR / ".env", override=False)


def env_bool(name, default=False):
    return os.environ.get(name, "1" if default else "0").strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def env_list(name, default=""):
    return [
        item.strip()
        for item in os.environ.get(name, default).split(",")
        if item.strip()
    ]


def env_positive_int(name, default):
    raw_value = os.environ.get(name, str(default)).strip()
    try:
        value = int(raw_value)
    except ValueError as exc:
        raise ImproperlyConfigured(f"{name} must be a positive integer") from exc
    if value <= 0:
        raise ImproperlyConfigured(f"{name} must be a positive integer")
    return value


def add_tunnel_host(allowed_hosts, csrf_origins, debug, raw_host):
    """Add one explicit development tunnel host without weakening production."""
    hosts = list(allowed_hosts)
    origins = list(csrf_origins)
    raw_host = raw_host.strip()
    if not debug or not raw_host:
        return hosts, origins

    parsed = urlsplit(f"//{raw_host}")
    host = parsed.hostname
    try:
        port = parsed.port
    except ValueError as exc:
        raise ImproperlyConfigured(
            "DJANGO_TUNNEL_HOST must be one lowercase hostname without a scheme, "
            "port, path, or wildcard"
        ) from exc
    if (
        host is None
        or port is not None
        or parsed.username is not None
        or parsed.password is not None
        or parsed.path
        or parsed.query
        or parsed.fragment
        or host != raw_host.rstrip(".").lower()
        or "*" in host
        or "." not in host
    ):
        raise ImproperlyConfigured(
            "DJANGO_TUNNEL_HOST must be one lowercase hostname without a scheme, "
            "port, path, or wildcard"
        )

    if host not in hosts:
        hosts.append(host)
    origin = f"https://{host}"
    if origin not in origins:
        origins.append(origin)
    return hosts, origins


SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-only-secret")
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost")
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")
TUNNEL_HOST = os.environ.get("DJANGO_TUNNEL_HOST", "")
ALLOWED_HOSTS, CSRF_TRUSTED_ORIGINS = add_tunnel_host(
    ALLOWED_HOSTS,
    CSRF_TRUSTED_ORIGINS,
    DEBUG,
    TUNNEL_HOST,
)

if not DEBUG and SECRET_KEY == "dev-only-secret":
    raise RuntimeError("DJANGO_SECRET_KEY is not set for production")

SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", False)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", False)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", False)

# Launch policy: keep every learning feature open while the service grows.
# Set this to true later to reactivate the existing free/premium limits.
PREMIUM_GATING_ENABLED = env_bool("DJANGO_PREMIUM_GATING_ENABLED", False)
GENERATED_MISSION_WATCH_INTERVAL_SECONDS = env_positive_int(
    "DJANGO_GENERATED_MISSION_WATCH_INTERVAL_SECONDS", 30
)

if env_bool("DJANGO_SECURE_PROXY_SSL_HEADER", False) or (DEBUG and TUNNEL_HOST):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.naver',
    'allauth.socialaccount.providers.kakao',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko"

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
WHITENOISE_MANIFEST_STRICT = env_bool("DJANGO_WHITENOISE_MANIFEST_STRICT", False)

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


def social_app(provider):
    prefix = provider.upper()
    client_id = os.environ.get(f"{prefix}_OAUTH_CLIENT_ID", "").strip()
    secret = os.environ.get(f"{prefix}_OAUTH_CLIENT_SECRET", "").strip()
    if not client_id or not secret:
        return {}
    return {
        "APP": {
            "client_id": client_id,
            "secret": secret,
            "key": "",
        }
    }


SOCIALACCOUNT_ADAPTER = "core.adapters.SocialAccountAdapter"
SOCIALACCOUNT_FORMS = {"signup": "core.forms.SocialSignupForm"}
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_AUTHENTICATION = False
SOCIALACCOUNT_LOGIN_ON_GET = False
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        **social_app("google"),
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "OAUTH_PKCE_ENABLED": True,
    },
    "naver": social_app("naver"),
    "kakao": social_app("kakao"),
}
SOCIAL_LOGIN_PROVIDERS = tuple(
    provider
    for provider, config in SOCIALACCOUNT_PROVIDERS.items()
    if config.get("APP")
)

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/missions/"
LOGOUT_REDIRECT_URL = "/login/"
